version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/stacks/node-next/template"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/stacks/spring-react/template/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/stacks/quarkus-angular/template/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/stacks/java-monolith/template"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/stacks/quarkus-angular/template/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/stacks/spring-react/template/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/stacks/node-next/template"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/stacks/java-monolith/template"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/stacks/quarkus-angular/template/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/stacks/spring-react/template/backend"
    schedule:
      interval: "weekly"
