apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wakaya-erp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raphaelparedes/wakaya-erp.git
    targetRevision: main
    path: ops/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: wakaya-erp-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # Produccion usa sync manual con aprobacion humana.
